name: Building vite files

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - name: Builds assets and vite-tag files
        run: |
          npm run build